name: PlantCAD_offical
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - htslib=1.3
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.1
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.11.14
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - biopython==1.86
      - causal-conv1d==1.5.0.post8
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - cyvcf2==0.31.4
      - datasets==3.3.2
      - dill==0.3.8
      - einops==0.8.1
      - filelock==3.20.0
      - fire==0.7.0
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2024.12.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - mamba-ssm==2.2.4
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.6.1
      - ninja==1.13.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==25.0
      - pandas==2.2.3
      - peft==0.14.0
      - pillow==12.0.0
      - propcache==0.4.1
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pyg-lib==0.4.0+pt25cpu
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyvcf3==1.0.4
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - six==1.17.0
      - sympy==1.13.1
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - torch==2.5.1+cu124
      - torch-cluster==1.6.3+pt25cpu
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt25cpu
      - torch-sparse==0.6.18+pt25cpu
      - torch-spline-conv==1.2.2+pt25cpu
      - torchaudio==2.5.1+cu124
      - torchvision==0.20.1+cu124
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.1.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.6.1
      - xgboost==2.0.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/zhang479/miniforge3/envs/PlantCAD_offical
